import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Invidious Entertainment handles information collected through invidiousentertainment.com.",
  alternates: { canonical: "/privacy" },
};

const LAST_UPDATED = "August 18, 2026";

/* NOTE FOR JEY — this describes what the site actually does today:
   one contact form, sent by email through Resend, and nothing else.
   No analytics, no advertising, no tracking cookies.

   If you later add Google AdSense, analytics, an email list, or any
   embedded third-party player, this page MUST be updated to say so
   before those go live. AdSense in particular requires disclosing
   third-party cookies and, for EEA/UK visitors, a consent mechanism. */

export default function Privacy() {
  return (
    <main className="px-7 pb-[120px] pt-[160px]">
      <div className="mx-auto max-w-[720px]">
        <span className="mb-[18px] inline-block text-[0.72rem] font-medium uppercase tracking-[0.32em] text-gold">
          Legal
        </span>
        <div className="mb-[30px] h-px w-16 bg-gold opacity-70" />
        <h1 className="mb-4 font-display text-[clamp(2.2rem,5vw,3rem)] font-semibold leading-[1.15]">
          Privacy Policy
        </h1>
        <p className="mb-[50px] text-[0.85rem] uppercase tracking-[0.15em] text-text-muted">
          Last updated {LAST_UPDATED}
        </p>

        <div className="prose">
          <p>
            This policy explains what information Invidious Entertainment
            (&ldquo;we&rdquo;, &ldquo;us&rdquo;) collects when you visit
            invidiousentertainment.com, why we collect it, and what we do with
            it. It applies only to this website.
          </p>

          <h2>Information you give us</h2>
          <p>
            The only information this site asks for is what you type into the
            contact form: your <strong>name</strong>, your{" "}
            <strong>email address</strong>, and your <strong>message</strong>.
            All three are required for the form to send.
          </p>
          <p>
            We use that information for one purpose: to read your message and
            reply to it. We do not sell it, rent it, trade it, or use it for
            advertising. We do not add you to a mailing list — there is no
            mailing list.
          </p>

          <h2>How your message reaches us</h2>
          <p>
            Contact form submissions are delivered to our inbox by{" "}
            <a href="https://resend.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">
              Resend
            </a>
            , an email delivery service acting as our processor. Your message
            passes through their systems in order to be sent. It arrives at{" "}
            <strong>info@invidiousentertainment.com</strong> and is retained in
            that inbox as ordinary business correspondence.
          </p>

          <h2>Cookies and tracking</h2>
          <p>
            This site sets <strong>no cookies</strong>. There is no analytics
            package, no advertising network, no tracking pixel, and no
            third-party script that follows you between sites. Fonts are served
            from this site&apos;s own domain rather than fetched from a third
            party, so simply reading a page does not report your visit to
            anyone.
          </p>
          <p>
            If that ever changes, this page will be updated before the change
            goes live, and it will say plainly what was added.
          </p>

          <h2>Hosting and server logs</h2>
          <p>
            The site is hosted by{" "}
            <a href="https://www.hostinger.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">
              Hostinger
            </a>
            . Like effectively all web hosts, their servers keep standard access
            logs — IP address, timestamp, requested page, browser user agent —
            for security and operational purposes. Those logs are generated by
            the hosting infrastructure, not by us, and are governed by
            Hostinger&apos;s own policy.
          </p>

          <h2>Links to other sites</h2>
          <p>
            Pages here link to external services such as Instagram and YouTube.
            Once you follow a link off this site, that service&apos;s privacy
            policy applies, not this one.
          </p>

          <h2>Your choices</h2>
          <p>
            You can browse this entire site without giving us anything — the
            contact form is the only place information is requested, and using
            it is voluntary. If you have written to us and want your message and
            details deleted, email{" "}
            <strong>info@invidiousentertainment.com</strong> and we will remove
            them from our inbox.
          </p>
          <p>
            Depending on where you live, you may have additional rights over
            your personal data, including the right to request access to it or
            its deletion. Use the same address to ask.
          </p>

          <h2>Children</h2>
          <p>
            This site is not directed at children under 13, and we do not
            knowingly collect information from them.
          </p>

          <h2>Changes to this policy</h2>
          <p>
            If this policy changes, the date at the top of the page changes with
            it. Material changes will be described rather than quietly folded
            in.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about this policy can go to{" "}
            <strong>info@invidiousentertainment.com</strong>, or through the{" "}
            <Link href="/#contact">contact form</Link>.
          </p>
        </div>
      </div>
    </main>
  );
}
